import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react'

import styles from '../styles/Home.module.css'
import { getRedirectUrl, userScopes } from '../api/auth'
import { getHash } from '../libs/getHash'
import { useInterval } from '../libs/interval'

const BANNER_IMAGE = [
  '/bg/banner-music-1.jpg',
  '/bg/banner-music-2.jpg',
  '/bg/banner-music-3.jpg',
  '/bg/banner-music-4.jpg',
  '/bg/banner-music-5.jpg',
  '/bg/banner-music-5.jpg',
]

export default function Home() {

  let [currentBanner, setBanner] = useState({
    value: BANNER_IMAGE[0],
  })
  let [count = 1, setCount] = useState(null)

  useInterval(() => {
    setBanner(BANNER_IMAGE[count] ?? BANNER_IMAGE[0])
    setCount(count+1)
    if (count === BANNER_IMAGE.length) {
      setCount(0)
    }
    console.log('currentBanner', currentBanner)
  }, 4000);

  useEffect(() => {
    let accessToken = getHash().access_token
    if (accessToken) {
      window.localStorage.setItem('spotifyAuthToken', accessToken)
      window.opener?.postMessage({ type: 'react-spotify-auth', accessToken }, '*')
    }
    let { spotifyAuthToken } = window.localStorage
    if(spotifyAuthToken) {
      window.location = '/profile'
    }
  })

  const handleLogin = (event) => {
    let clientID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENTID ?? ''
    let redirectUrl = process.env.NEXT_PUBLIC_URL ?? 'http://localhost:3000'
    event.preventDefault()

    const redirectUri = getRedirectUrl(
      {
        clientID,
        scopes: userScopes,
        redirectUrl,
      }
    )

    if (window.location !== window.parent.location) {
      const loginWindow = window.open(redirectUri)
      window.addEventListener('message', (event) => {
        if (event.data.type !== 'react-spotify-auth' || !event.data.accessToken) {
          return
        }

        loginWindow.close()
      }, false)
    } else {
      window.location = redirectUri
    }
  }

  return (
    // login to spotify
    <div className={styles.container}>
      <Head>
        <title>Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={
        {
          backgroundImage: `url(${currentBanner})`,
          transition: 'background-image 1s linear',
        }
      } className={`${styles.banner} min-w-full min-h-full brightness-75`} id="banner">

      </div>
      <main className={`${styles.main}`}>
        <h1 className="font-bold text-5xl text-white">
          Your Spotify TOP 10
        </h1>

        <p className="py-10 text-base px-5 text-white">
          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        </p>

        <button className='px-10 py-4 bg-spotify rounded-full font-semibold hover:shadow-cyan-500/50 shadow-xl hover:brightness-110'
          onClick={(event) => handleLogin(event)}>
          <img src=""></img>
          Log in with Spotify
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
