import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react'

import styles from '../styles/Home.module.css'
import { getRedirectUrl, userScopes } from '../api/auth'
import { getHash } from '../libs/getHash'
import { useInterval } from '../libs/interval'
import { handleLogin } from '../api/auth'

const BANNER_IMAGE = [
  '/bg/banner-music-1.jpg',
  '/bg/banner-music-2.jpg',
  '/bg/banner-music-3.jpg',
  '/bg/banner-music-4.jpg',
  '/bg/banner-music-5.jpg',
  '/bg/banner-music-5.jpg',
]

export default function Home() {

  let [currentBanner, setBanner] = useState({
    value: BANNER_IMAGE[0],
  })
  // let [count = 1, setCount] = useState(null)

  // useInterval(() => {
    // setBanner(BANNER_IMAGE[count] ?? BANNER_IMAGE[0])
    // setCount(count+1)
    // if (count === BANNER_IMAGE.length) {
    //   setCount(0)
    // }
  // }, 4000);

  useEffect(() => {
    let accessToken = getHash().access_token
    if (accessToken) {
      window.localStorage.setItem('spotifyAuthToken', accessToken)
      window.opener?.postMessage({ type: 'react-spotify-auth', accessToken }, '*')
    }
    let { spotifyAuthToken } = window.localStorage
    if(spotifyAuthToken) {
      window.location = '/profile'
    }
    const rand = Math.round(Math.random() * 5);
    setBanner(BANNER_IMAGE[rand] ?? BANNER_IMAGE[0])
  })

  return (
    // login to spotify
    <div className={styles.container}>
      <Head>
        <title>Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={
        {
          backgroundImage: `url(${currentBanner})`,
          transition: 'background-image 1s linear',
        }
      } className={`${styles.banner} min-w-full min-h-full brightness-75`} id="banner">

      </div>
      <main className={`${styles.main}`}>
        <h1 className="font-bold text-5xl text-white">
          Your Spotify Top 10
        </h1>

        <p className="py-10 text-base px-5 text-white">
          Get your spotify profiles, top 10 lists, and mores.
        </p>

        <button className='px-10 py-4 bg-spotify rounded-full font-semibold hover:shadow-cyan-500/50 shadow-xl hover:brightness-110 flex'
          onClick={(event) => handleLogin(event)}>
          <img src="/ic-spotify-30.png"></img>
          <div className="px-3">Log in with Spotify</div>
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
