import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'

import styles from '../styles/Profile.module.css'
import TopCard from '../components/TopCard'
import TopList from '../components/List'

import { topArtist } from '../datas/topArtists'
import { topSong } from '../datas/topSongs'

export default function Profile() {
  let firstArtists = topArtist[0]
  let secondArtists = [
    topArtist[1],
    topArtist[2]
  ]
  let [ topArtists = [], setTopArtists ] = useState({
    value: topArtist,
  })
  let firstSongs = topSong[0]
  let secondSongs = [
    topSong[1],
    topSong[2]
  ]
  let [ topSongs = [], setTopSongs ] = useState({
    value: topSong
  })
  return (
    // login to spotify
    <div className={`${styles.container} dark:bg-gray-900`}>
      <Head>
        <title>Spotify Top 10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`max-w-xl mx-auto w-screen ${styles.main} md:pt-10`}>
        {/* Banner Home */}
        <div className={`bg-gradient-to-tr from-violet-500 to-pink-500 ${styles.topCard} flex`}>
          <div className='px-10 py-5'>
            <h1 className='text-4xl font-bold tracking-wide'>
              Top Artists
            </h1>
            <h2 className='pt-5'>
              Last Week
            </h2>
            <div className='pt-7 pb-3 flex'>
              <div className=''>
                <TopCard 
                  name={firstArtists.name} 
                  idx="1" 
                  imgSrc={firstArtists.images[1].url}
                  isTop={true}
                  width={320}
                  />
              </div>
              <div className=''>
                {
                  secondArtists.map((item, idx) => {
                    return <TopCard key={idx}
                      name={item.name} 
                      idx={idx+2} 
                      imgSrc={item.images[2].url}
                      isTop={false}
                      width={160}
                      />
                  })
                }
              </div>
            </div>
          </div>
        </div>
        <div className='pb-20'>
          {/* table */}
          <TopList 
            items={topArtists.value}
            isArtists={true}
          />
        </div>
        <div className={`bg-gradient-to-br from-indigo-500 to-cyan-500 ${styles.topCard} flex`}>
          <div className='px-10 py-5'>
            <h1 className='text-4xl font-bold tracking-wide'>
              Top Songs
            </h1>
            <h2 className='pt-5'>
              Last Week
            </h2>
            <div className='pt-7 pb-3 flex'>
              <div className=''>
                <TopCard 
                  name={firstSongs.name} 
                  idx="1" 
                  imgSrc={firstSongs.album.images[1].url}
                  isTop={true}
                  width={320}
                  />
              </div>
              <div className=''>
                {
                  secondSongs.map((item, idx) => {
                    return <TopCard key={idx}
                      name={item.name} 
                      idx={idx+2} 
                      imgSrc={item.album.images[1].url}
                      isTop={false}
                      width={160}
                      />
                  })
                }
              </div>
            </div>
          </div>
        </div>
        <div className='pb-20'>
          {/* table */}
          <TopList 
            items={topSongs.value}
            isArtists={false}
          />
        </div>
      </main>
    </div>
  )
}